### ISSUE TITLE
Maximum number of traversals

### ISSUE THREAD

**Issue by martijn0x76** [ewilded/psychoPATH#1]
Hi,

I just did a quick test on a local DVWA to test the payload generation to test LFI. This works fine! Good work.

The default depth / number of traversals is 8. I changed it to 16 and expected to see more requests fired to the target. But nothing changed to the count of requests or depth.

**Comment by ewilded** [comment]
Thanks for reporting this. There was no callback connected to the event of changing that number. Introduced with https://github.com/ewilded/psychoPATH/commit/c2fcdd76af43fc221fa8a6bc4b8f3e685675a01a
