### ISSUE TITLE
View problem

### ISSUE THREAD

**Issue by ftteh** [ewilded/psychoPATH#5]
Hi,I am trying to use your psychopath in the burp but the view isn't complete I can't see the bottom of the page of psychopath.Thanks

**Comment by ewilded** [comment]
Please attach a screenshot. Also, info on what screen resolution do you use would also be helpful.

Thanks,
Julian

**Comment by ftteh** [comment]
Resolution is 1366x768.There is no way I can scroll the page.The screenshot:
![pschopath](https://user-images.githubusercontent.com/30791174/39079044-dda9eb7c-4545-11e8-95d3-c440e01afe65.png)Thanks

**Comment by ewilded** [comment]
Hi, many thanks for the screenshot - it helped a lot :) You are using the older version of the plugin (the one that's currently available in the Burp App store) with the old interface. The current version (available in this repo) has completely new UI, which should be properly scalable. Also, options are divided into several tabs, so scrolling should not even be necessary (there should be enough space in each tab to fit all the elements in most resolutions). You can either:
1) download the jar from this repo
2) build it yourself from this repo
3) wait until the new version is processed by Portswigger (I submitted it over 2 weeks ago, now it's on their side) and put into the Bapp Store (if you installed the plugin from there, it should update automatically or at least give you a notification that a new version is available).
![new_ui](https://user-images.githubusercontent.com/1158719/39080402-c96b8eda-452d-11e8-93eb-047ca222ce87.png)

**Comment by ftteh** [comment]
Really thanks for your reply,I don't know whether all the tabs work fine,but I managed to find two pages still having the issue.
![psyc](https://user-images.githubusercontent.com/30791174/39094976-4dad7bde-466b-11e8-92c1-2efc8e1d082b.png)

And also this page
![pschopath](https://user-images.githubusercontent.com/30791174/39095029-22dd48f2-466c-11e8-98af-b8f05cd5c4b2.png)
when added too many patterns I am unable to see the patterns at the bottom but I managed to move to the hidden from display pattern using the arrow key( the orange highlight once you clicked it).I think have to make this list scrollable.Thanks

**Comment by ewilded** [comment]
Hi,

Thanks a lot for these details, it helps me fixing these problems before the new version hits the store.

I just did some adjustments and - this time - also some tests on a lower resolution box. Try it now and let me know whether we can close this issue :)

**Comment by ftteh** [comment]
That's good.Everything works fine now.You can now close this issue.Thanks

**Comment by ewilded** [comment]
Awesome :grin:
